config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  get 'admin/create'
  get 'admin/new'
  get 'admin/index'
  
  get '/signup' => 'admins#new'
  post '/admin' => 'admins#create'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "admins#index"
  get "/feedbackform", to: "feedbackforms#index"
  get "/employee", to: "employees#index" 
  get "/student", to: "students#index"
  get "/emp", to: "employees#edit"
  resources  :employees 
  resources :students
  resources :feedbackforms
end

app/models/admin.rb
class Admin < ApplicationRecord
    has_secure_password
    has_one :admin
    validates :user_name, presence: true, length: { minimum: 3 }
    validates :email, presence: true, uniqueness: true
    validates :password, length: { in: 5..10 }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/employee.rb
class Employee < ApplicationRecord
end

app/models/feedbackform.rb
class Feedbackform < ApplicationRecord
end

app/models/student.rb
class Student < ApplicationRecord
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
 
  def index
    @feedbackforms = Feedbackform.all
    @employees = Employee.all
    @students = Student.all
    response = HTTParty.get("http://api.weatherstack.com/current?access_key=5c8c1958b54deb874ab63dce4c5e5b78&query=New%20York")
    Rails.logger.info response.code
    Rails.logger.info response.body
    Rails.logger.info response.to_a
    a = JSON.parse(response.body)
    @query = a["request"]["query"]
    @wind_speed = a["current"]["wind_speed"]
    @temperature = a["current"]["temperature"]
    @precip = a["current"]["precip"]
    @pressure = a["current"]["pressure"]
    @humidity = a["current"]["humidity"]
    @visibility = a["current"]["visibility"]
    @cloudcover = a["current"]["cloudcover"]
    @feelslike = a["current"]["feelslike"]
  end

  def create
    @admin = Admin.new(admin_params)
    if @admin.save
        flash[:notice]="Signup successful"
    else
        Rails.logger.info @admin.errors.full_messages
        flash[:notice]= @admin.errors.full_messages
        redirect_to '/signup'
    end
  end

  private
  def admin_params
    params.require(:admin).permit(:user_name, :email, :password)
  end
    
  def new
    @admin = Admin.new
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def current_admin
        @current_admin ||= Admin.find(session[:admin_id]) if session[:admin_id]
    end
    helper_method :current_admin
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
    def index
       @employees = Employee.all
    end

    def new
       @employee = Employee.new
    end

    def edit
       @employee = Employee.find(params[:id])
    end

    def update
       @employee = Employee.find(params[:id])
       @employee.update(employees_params)
       redirect_to root_path
    end
    
    def create
       employee = Employee.new(employees_params)
       employee.save 
       redirect_to root_path
    end 

    private
    def employees_params
       params.require(:employee).permit(:name, :email, :empid)
    end
end

app/controllers/feedbackforms_controller.rb
class FeedbackformsController < ApplicationController
    def index
       @feedbackforms = Feedbackform.all
    end

    def new
       @feedbackform =  Feedbackform.new
    end

    def create
       feedbackform =  Feedbackform.new(feedbackforms_params)
       feedbackform.save 
       redirect_to root_path
    end

    private
    def feedbackforms_params
        params.require(:feedbackform).permit(:name, :rating, :comments)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    admin = Admin.find_by(params[:admin_name])
    if admin && admin.authenticate(params[:password])
      session[:admin_id] = admin.id
      flash[:notice]="Login successful"
      redirect_to '/'
    else
      flash[:notice]="Invalid Email or Password"
      redirect_to '/login'
    end
  end

  def destroy
    session[:admin_id] = nil
    flash[:notice]="Logged Out"
    redirect_to '/login'
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
    def index
      @students = Student.all
    end

    def new
      @student =  Student.new
    end

    def edit
      @student=Student.find(params[:id])
    end

    def create
      @student = Student.new(students_params)
      @student.save  
      redirect_to root_path     
    end

    def update
      @student = Student.find(params[:id])
      @student.update(students_params)
      redirect_to root_path
    end

    def destroy   
      @student = Student.find(params[:id])   
      @student.destroy    
      redirect_to root_path   
    end 

    def show
      @student = Student.find(params[:id])
    end
    
    private
    def students_params
      params.require(:student ).permit(:name, :email, :studentid)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/feedbackforms_helper.rb
module FeedbackformsHelper
end

app/helpers/incomes_helper.rb
module IncomesHelper
end

app/helpers/mains_helper.rb
module MainsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/admins/_navbar.html.erb
<div id="wrapper">
    <div class="navbar-custom">
        <div class="container-fluid">
            <ul class="list-unstyled topnav-menu float-start mb-0">
                <li><a class="nav-link" href="/student">student</a></li>
                <li><a class="nav-link" href="/feedbackform">feedbackform</a></li>
                <li><a class="nav-link" href="/employee">employee</a></li>
                <li><a class="nav-link" href="/logout">Logout</a></li>
                <li><a class="nav-link" href="/login">Login</a></li>
                <ul>
        </div>
    </div>
</div>

app/views/admins/_weather_report.html.erb
<div class="col-md-6 col-xl-6">
   <div class="card" id="tooltip-container">
        <div class="card-body bg-light">
            <h5>Weather Report</h5>
                <p><strong>City: </strong><%= @query %></p>
                <p><strong>wind Speed: </strong><%= @wind_speed %></p>
                 <p><strong>Temperature: </strong><%= @temperature %></p>
                <p><strong>precip: </strong><%= @precip %></p>
                <p><strong>Pressure: </strong><%= @pressure %></p>
                <p><strong>Humidity: </strong><%= @humidity %></p>
                <p><strong>Visibility: </strong><%= @visibility %></p>
                <p><strong>Cloudcover: </strong><%= @cloudcover %></p>
                <p><strong>Feelslike: </strong><%= @feelslike %></p>
        </div>
    </div>
</div>

app/views/admins/create.html.erb
<h1>User#create</h1>
<p>Find me in app/views/user/create.html.erb</p>

app/views/admins/index.html.erb
<% if current_admin %>
    <div id="wrapper">
        <%= render "admins/navbar" %>
        <%= render "admins/sidebar" %>
        <%= render "admins/content" %>
    </div>
<% else %>
    <%= link_to 'Signup', '/signup'%><br>
    <%= link_to 'Login', '/login'%>
<% end %>

app/views/admins/new.html.erb
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

<%= form_for :admin, url: '/admin' do |form| %>
<div id="signup">
   <div class="container pt-3">
       <div id="signup-row" class="row justify-content-center align-items-center">
          <div id="signup-column" class="col-md-6">
              <div id="signup-box" class="col-md-12">
                <h3 class="text-center pb-3">SignUp</h3>
                <div>
                   <% if flash[:notice].present?%>
                        <%flash[:notice].each do |message| %>
                        <p class="text-danger"><%= message %></p>
                   <%end%>
                   <%end%>
                </div>
                
<div class="form-group">
        <strong><%= form.label :user_Name %></strong><br>
        <%= form.text_field :user_name, class: 'form-control' %>
</div>

<div class="form-group">
        <strong><%= form.label :email %></strong><br>
        <%= form.text_field :email, class: 'form-control' %>
</div>

<div class="form-group mb-2">
        <strong><%= form.label :password %></strong><br>
        <%= form.password_field :password, class: 'form-control' %>
</div>

<div class="form-group">
        <%=  submit_tag("Create Account") %>
</div>
<%= link_to 'Login', '/login'%>
</div>
</div>
</div>
</div>
</div>
</div>
<% end %>

app/views/employees/_employee_details.html.erb
<div class="col-md-6 col-xl-6">
    <div class="card" id="tooltip-container3">
        <div class="card-body ">
            <h5>Employee Details</h5>
            <table class="table table-bordered">
            <thead>
            <tr>
                <th scope="col">Name</th>
                <th scope="col">Email</th>
                <th scope="col">Employee Id</th>
            </tr>
            </thead>
            <tbody>
                <% @employees.each do |e| %>
                <tr>
                    <td><%= e.name.capitalize() %></td>
                    <td><%= e.email%></td>
                    <td><%= e.empid%></td>
                </tr>
            <% end %>
            </tbody>
            </table>
        </div>
    </div>
</div>

app/views/employees/edit.html.erb
 <div id="wrapper">
    <%= render "mains/navbar" %>
    <%= render "mains/sidebar" %>
      <div class="content">
        <div class="container-fluid">
          <div class="container">
          
              <h2>edit page</h2>
              <%= form_with(model: @employee, local: true) do |form| %>
              <h1>Employee registration</h1>

          <div class="form-group p-2">
              <strong><%= form.label :name %></strong><br>
              <%= form.text_field :name, class:'form-control' %>
           </div>

           <div class="form-group p-2">
              <strong><%= form.label :email %></strong><br>
              <%= form.email_field :email, class: 'form-control' %>
           </div>

           <div class="form-group p-2">
              <strong><%= form.label :empid %></strong><br>
              <%= form.text_field :empid, class: 'form-control' %>
           </div>

           <div class="form-group p-2">
              <%= form.submit :register, class: 'form-control btn-light' %>
           </div>

        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/employees/index.html.erb
<div id="wrapper">
  <%= render "admins/navbar" %>
  <%= render "admins/sidebar" %>
  <div class="content-page">
    <div class="content">
      <div class="container-fluid">
        <div class="container">
            <%= form_with scope: :employee, url: employees_path, local: true do |form| %>
            <h1>Employee Registration</h1>

        <div class="form-group p-2">
            <strong><%= form.label :name %></strong><br>
            <%= form.text_field :name, class:'form-control' %>
        </div>

        <div class="form-group p-2">
            <strong><%= form.label :email %></strong><br>
            <%= form.email_field :email, class: 'form-control' %>
        </div>

        <div class="form-group p-2">
            <strong><%= form.label :empid %></strong><br>
            <%= form.text_field :empid, class: 'form-control' %>
        </div>

        <div class="form-group p-2">
            <%= form.submit :register, class: 'form-control btn-light' %>
        </div>
        <% end %>
          <a href="/">home page</a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/feedbackforms/_feedbackform.html.erb
<div class="col-md-6 col-xl-5">
    <div class="card" id="tooltip-container1">
        <div class="card-body">
            <h5>Feedback Details</h5>
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th scope="col">Name</th>
                        <th scope="col">Rating</th>
                        <th scope="col">Comments</th>
                    </tr>
                </thead>
                <tbody>
                    <% @feedbackforms.each do |f| %>
                    <tr>
                        <td><%= f.name.capitalize() %></td>
                        <td><%= f.rating%></td>
                        <td><%= f.comments%></td>
                    </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
    </div>
</div>

app/views/feedbackforms/index.html.erb
<div>
  <h2>feedback Form</h2>
  <%= form_with scope: :feedbackform, url: feedbackforms_path, local: true do |form| %>

  <div class="form-group p-2">
      <strong><%= form.label :name %></strong><br>
      <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group p-2">
      <strong><%= form.label :Rating %></strong><br>
      <%= form.radio_button :rating, "1" %>
      <%= form.label :rating, "1" %><br>
      <%= form.radio_button :rating, "2" %>
      <%= form.label :rating, "2" %><br>
      <%= form.radio_button :rating, "3" %>
      <%= form.label :rating, "3" %><br>
      <%= form.radio_button :rating, "4" %>
      <%= form.label :rating, "4" %><br>
      <%= form.radio_button :rating, "5" %>
      <%= form.label :rating, "5" %><br>
  </div>

  <div class="form-group p-2">
      <strong><%= form.label :comments %></strong><br>
      <%= form.text_area :comments, size: "30x6",placeholder: 'enter comments', class: 'form-control' %>
  </div>

  <div class="form-group p-2">
      <%= form.submit :submit, class: 'form-control btn-dark' %>
  </div>

  <% end %>
<a href="/">home page</a>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>

  <html lang="en">

  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">


    <title>Dashboard 3 | UBold - Responsive Admin Dashboard Template</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta content="A fully featured admin theme which can be used to build CRM, CMS, etc." name="description">
    <meta content="Coderthemes" name="author">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <!-- App favicon -->


    <!-- App css -->
    <link href="/css/app.min.css" rel="stylesheet" type="text/css" id="app-style">
    <!-- icons -->
    <link href="/css/icons.min.css" rel="stylesheet" type="text/css" id="app-style">
    <%= javascript_importmap_tags %>





  </head>

  <!-- body start -->

<body class="" data-layout-mode="default" data-layout-color="light" data-topbar-color="dark" data-menu-position="fixed"
  data-leftbar-color="light" data-leftbar-size="default" data-sidebar-user="false">

  <!-- Begin page -->
  <div id="wrapper">

    <!-- Topbar Start -->

    <!-- end Topbar -->
    <div>

      <%= yield %>
      <!-- Vendor js -->
      <script src="./scripts/vendor.min.js.download"></script>

      <!-- Chart JS -->
      <script src="./scripts/Chart.bundle.min.js.download"></script>

      <script src="./scripts/moment.min.js.download"></script>
      <script src="./scripts/jquery.scrollTo.min.js.download"></script>

      <!-- Chat app -->
      <script src="./scripts/jquery.chat.js.download"></script>

      <!-- Todo app -->
      <script src="./scripts/jquery.todo.js.download"></script>

      <!-- Dashboard init JS -->
      <script src="./scripts/dashboard-3.init.js.download"></script>

      <!-- App js-->
      <script src="./Dashboard 3 _ UBold - Responsive Admin Dashboard Template_files/app.min.js.download"></script>

</body>

</html>

app/views/mains/_navbar.html.erb
<div id="wrapper">
    <div class="navbar-custom">
        <div class="container-fluid">
            <ul class="list-unstyled topnav-menu float-start mb-0">
                <li><a class="nav-link" href="/student">student</a></li>
                <li><a class="nav-link" href="/feedbackform">feedbackform</a></li>
                <li><a class="nav-link" href="/employee">employee</a></li>
                <li><a class="nav-link" href="/inc">Income</a></li>
                <li><a class="nav-link" href="/logout">Logout</a></li>
                <li><a class="nav-link" href="/login">Login</a></li>
                <ul>
        </div>
    </div>
</div>

app/views/students/_student_details.html.erb
<div class="col-md-6 col-xl-7">
    <div class="card" id="tooltip-container">
        <div class="card-body">
            <h5>Student Details</h5>
            <table class="table table-bordered">
            <thead>
            <tr>
                <th scope="col">Name</th>
                <th scope="col">Email</th>
                <th scope="col">Student Id</th>
                <th scope="col">Edit</th>
                <th scope="col">Delete</th>
            </tr>
            </thead>
            <tbody>
                <% @students.each do |student| %>
                <tr>
                    <td><%= student.name.capitalize() %></td>
                    <td><%= student.email%></td>
                    <td><%= student.studentid%></td>
                    <td><%= link_to "Edit", edit_student_path(student) %></td>
                    <td> <%= button_to 'Delete',  "/students/#{student.id}",  method: :delete %></td>
                </tr>
                <% end %>
            </tbody>
            </table>
        </div>
    </div>
</div>

app/views/students/edit.html.erb
 <div id="wrapper">
   <%= render "admins/navbar" %>
   <%= render "admins/sidebar" %>
   <div class="content-page">
     <div class="content">
        <div class="container">
           <%= form_for @student, url:{action:"update"} do |form| %>
           <h1>student edit form</h1>
           
          <div class="form-group p-2">
              <strong><%= form.label :name %></strong><br>
              <%= form.text_field :name, class: 'form-control bg-light' %>
           </div>

           <div class="form-group p-2">
              <strong><%= form.label :email %></strong><br>
              <%= form.email_field :email, class: 'form-control  bg-light', placeholder: 'name@gmail.com' %>
           </div>

           <div class="form-group p-2">
              <strong><%= form.label :studentid %></strong><br>
              <%= form.text_field :studentid, class: 'form-control  bg-light' %>
           </div>

           <div class="form-group p-2">
              <%= form.submit :submit, class: 'form-control btn-dark' %>
           </div>

          <% end %>
          <a href="/">home page</a>
        </div>
      </div>
    </div>
 </div>

app/views/students/index.html.erb
 <div id="wrapper">
    <%= render "admins/navbar" %>
    <%= render "admins/sidebar" %>
    <div class="content-page">
      <div class="content">
         <div class="container">
            <%= form_with scope: :student, url: student_path, local: true do |form| %>
            <h1>student registration form</h1>

         <div class="form-group p-2">
              <strong><%= form.label :name %></strong><br>
              <%= form.text_field :name, class: 'form-control bg-light' %>
         </div>

         <div class="form-group p-2">
              <strong><%= form.label :email %></strong><br>
              <%= form.email_field :email, class: 'form-control  bg-light', placeholder: 'name@gmail.com' %>
         </div>

         <div class="form-group p-2">
              <strong><%= form.label :studentid %></strong><br>
              <%= form.text_field :studentid, class: 'form-control  bg-light' %>
         </div>

         <div class="form-group p-2">
              <%= form.submit :submit, class: 'form-control btn-dark' %>
         </div>

         <% end %>
      <a href="/">home page</a>

     </div>
   </div>
  </div>
</div>

app/views/students/new.html.erb
<div class="container">   
  <%= form_for @student, url: {action: :create} do |f| %>   
   <div class="form-group p-2">
        <strong><%= form.label :name %></strong><br>
        <%= form.text_field :name, class: 'form-control bg-light' %>
    </div>

    <div class="form-group p-2">
        <strong><%= form.label :email %></strong><br>
        <%= form.email_field :email, class: 'form-control  bg-light', placeholder: 'name@gmail.com' %>
    </div>

    <div class="form-group p-2">
        <strong><%= form.label :studentid %></strong><br>
        <%= form.text_field :studentid, class: 'form-control  bg-light' %>
    </div>

    <div class="form-group p-2">
        <%= form.submit :submit, class: 'form-control btn-dark' %>
    </div> 

  <% end %>  
  <a href="/">home page</a> 
</div>  

app/views/students/show.html.erb
<div class="container">

    <h3>Add a student</h3>

    <div>

        <label>Name</label>

        <%= @student.name %>

    </div>
    <div>

        <label>Email</label>

        <%= @student.email %>

    </div>



    <div>

        <label>StudentId</label>

        <%= @student.studentid%>

    </div>



    <div>

        <%= link_to 'Back',"/" %>

    </div>



</div>